# Generated by Django 5.1 on 2024-09-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePaymentsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_client', models.TextField(max_length=200, null=True)),
                ('email_client', models.TextField(max_length=200, null=True)),
                ('serie', models.CharField(max_length=4, null=True)),
                ('number', models.IntegerField(null=True)),
                ('link', models.TextField(null=True)),
                ('pdf_link', models.TextField(null=True)),
                ('xml_link', models.TextField(null=True)),
                ('accepted_by_sunat', models.BooleanField(default=False, null=True)),
                ('string_for_qr_code', models.TextField(null=True)),
            ],
            options={
                'db_table': 'invoice_payment',
            },
        ),
    ]
