# Generated by Django 5.0.1 on 2024-09-21 00:25

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('product', '0001_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('CLIENT', 'Cliente'), ('ADMIN', 'Administrador')], default='CLIENT', max_length=100)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='UserClientModel',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('password', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code_google', models.CharField(blank=True, max_length=200, null=True)),
                ('document_number', models.CharField(blank=True, max_length=10, null=True)),
                ('ruc', models.CharField(blank=True, max_length=10, null=True)),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_superuser', models.BooleanField(default=False, null=True)),
                ('is_staff', models.BooleanField(default=False, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='profile_client.rolemodel')),
            ],
            options={
                'db_table': 'user_client',
            },
        ),
        migrations.CreateModel(
            name='UserAddressModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250, null=True)),
                ('street', models.CharField(max_length=100, null=True)),
                ('street_number', models.CharField(max_length=50, null=True)),
                ('reference', models.TextField(null=True)),
                ('user_client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_address',
            },
        ),
        migrations.CreateModel(
            name='UserFavoritesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_product', to='product.productmodel')),
                ('user_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_favorite',
            },
        ),
        migrations.CreateModel(
            name='UserOrderModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to='purchases.ordermodel')),
                ('user_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_order',
            },
        ),
        migrations.CreateModel(
            name='UserPaymentMethodModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField(null=True)),
                ('payment_method', models.CharField(max_length=100)),
                ('payment_number', models.CharField(max_length=100, null=True)),
                ('card_type', models.CharField(max_length=100, null=True)),
                ('card_name', models.CharField(max_length=100, null=True)),
                ('country_code', models.CharField(max_length=10, null=True)),
                ('installments', models.IntegerField(null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('user_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_payment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_payment_method',
            },
        ),
    ]
