# Generated by Django 5.1 on 2024-09-11 16:46

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserClientModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('password', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code_google', models.CharField(blank=True, max_length=200, null=True)),
                ('document_number', models.CharField(blank=True, max_length=10, null=True)),
                ('ruc', models.CharField(blank=True, max_length=10, null=True)),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_client',
            },
        ),
    ]
