# Generated by Django 5.1 on 2024-09-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclientmodel',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
