# Generated by Django 5.1 on 2024-09-12 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('profile_client', '0002_alter_userclientmodel_last_name'),
        ('purchases', '0002_alter_orderdeliverymodel_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddressModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('street', models.CharField(max_length=100)),
                ('street_number', models.CharField(max_length=50)),
                ('reference', models.TextField(null=True)),
                ('user_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to='profile_client.userclientmodel')),
            ],
            options={
                'db_table': 'user_address',
            },
        ),
        migrations.CreateModel(
            name='UserFavoritesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_product', to='product.productmodel')),
                ('user_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_user', to='profile_client.userclientmodel')),
            ],
            options={
                'db_table': 'user_favorite',
            },
        ),
        migrations.CreateModel(
            name='UserOrderModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to='purchases.ordermodel')),
            ],
            options={
                'db_table': 'user_order',
            },
        ),
        migrations.CreateModel(
            name='UserPaymentMethodModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=100)),
                ('patment_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payment', to='profile_client.userclientmodel')),
                ('user_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_payment_method', to='profile_client.userclientmodel')),
            ],
            options={
                'db_table': 'user_payment_method',
            },
        ),
    ]
