# Generated by Django 5.1 on 2024-09-12 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_client', '0003_useraddressmodel_userfavoritesmodel_userordermodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpaymentmethodmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='userordermodel',
            name='user_client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_client', to='profile_client.userclientmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraddressmodel',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='useraddressmodel',
            name='street',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useraddressmodel',
            name='street_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userpaymentmethodmodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='userpaymentmethodmodel',
            name='user_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_payment', to='profile_client.userclientmodel'),
        ),
    ]
