# Generated by Django 5.1 on 2024-09-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_client', '0007_alter_useraddressmodel_user_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclientmodel',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
