# Generated by Django 5.1 on 2024-09-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_client', '0008_userclientmodel_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclientmodel',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
