# Generated by Django 5.1 on 2024-09-19 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_client', '0010_alter_userclientmodel_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('ADMIN', 'Administrador'), ('CLIENT', 'Cliente')], default='CLIENT', max_length=100)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.AddField(
            model_name='userclientmodel',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userclientmodel',
            name='role_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='profile_client.rolemodel'),
        ),
    ]
