# Generated by Django 5.1 on 2024-09-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_client', '0011_rolemodel_userclientmodel_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclientmodel',
            name='is_staff',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='userclientmodel',
            name='is_superuser',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
