# Generated by Django 5.1 on 2024-09-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_client', '0013_remove_userclientmodel_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclientmodel',
            name='is_staff',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
