# Generated by Django 5.1 on 2024-09-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('profile_client', '0014_userclientmodel_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userclientmodel',
            old_name='role_id',
            new_name='role',
        ),
        migrations.AddField(
            model_name='userclientmodel',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='userclientmodel',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='name',
            field=models.CharField(choices=[('CLIENT', 'Cliente'), ('ADMIN', 'Administrador')], default='CLIENT', max_length=100),
        ),
    ]
