# Generated by Django 5.1 on 2024-09-19 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_client', '0015_rename_role_id_userclientmodel_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclientmodel',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='profile_client.rolemodel'),
        ),
    ]
