# Generated by Django 5.1 on 2024-09-07 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productcategory_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productcategory',
            table='product_category',
        ),
        migrations.AlterModelTable(
            name='productmodel',
            table='product',
        ),
    ]
