# Generated by Django 5.1 on 2024-09-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productcategorymodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='discount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
