# Generated by Django 5.1 on 2024-09-10 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productcategory_table_alter_productmodel_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='ProductCategoryModel',
        ),
    ]
