# Generated by Django 5.1 on 2024-09-17 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productmodel_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbrandmodel',
            name='product',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_brand', to='product.productbrandmodel'),
        ),
        migrations.AlterField(
            model_name='productdetailmodel',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_detail', to='product.productmodel'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='product.productcategorymodel'),
        ),
    ]
