# Generated by Django 5.1 on 2024-09-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_productbrandmodel_product_productmodel_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='code',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
