# Generated by Django 5.0.1 on 2024-09-20 21:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productmodel_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbrandmodel',
            options={'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='productcategorymodel',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='productdetailmodel',
            options={'verbose_name': 'Detalle del producto', 'verbose_name_plural': 'Detalles del producto'},
        ),
        migrations.AlterModelOptions(
            name='productimagemodel',
            options={'verbose_name': 'Imagen del producto', 'verbose_name_plural': 'Imágenes del producto'},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='productcategorymodel',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
