# Generated by Django 5.0.1 on 2024-09-20 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_productbrandmodel_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetailmodel',
            old_name='denifit',
            new_name='benifit',
        ),
        migrations.RenameField(
            model_name='productdetailmodel',
            old_name='size',
            new_name='weight',
        ),
    ]
