# Generated by Django 5.1 on 2024-09-11 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=200, unique=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderIdentificationModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('document_number', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('ruc', models.CharField(max_length=10)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_identification', to='purchases.ordermodel')),
            ],
            options={
                'db_table': 'order_identification',
            },
        ),
        migrations.CreateModel(
            name='OrderDetailModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order_detail', to='product.productmodel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='purchases.ordermodel')),
            ],
            options={
                'verbose_name': 'Order Detail',
                'verbose_name_plural': 'Order Details',
                'db_table': 'order_detail',
                'ordering': ['order', 'product'],
            },
        ),
        migrations.CreateModel(
            name='OrderDeliveryModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=250)),
                ('province', models.CharField(max_length=250)),
                ('district', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('street', models.CharField(max_length=250)),
                ('street_number', models.CharField(max_length=50)),
                ('reference', models.CharField(max_length=250, null=True)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_delivery', to='purchases.ordermodel')),
            ],
            options={
                'db_table': 'order_delivery',
            },
        ),
        migrations.CreateModel(
            name='OrderPaymentModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('patment_date', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_payment', to='purchases.ordermodel')),
            ],
            options={
                'db_table': 'order_payment',
            },
        ),
        migrations.CreateModel(
            name='OrderStoreModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=250)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_store', to='purchases.ordermodel')),
            ],
            options={
                'db_table': 'order_store',
            },
        ),
        migrations.CreateModel(
            name='OrderUserTempModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=200)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_user_temp', to='purchases.ordermodel')),
            ],
            options={
                'db_table': 'order_user_temp',
            },
        ),
    ]
