# Generated by Django 5.0.1 on 2024-09-21 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=200, null=True, unique=True)),
                ('total', models.FloatField()),
                ('total_discount', models.FloatField(null=True)),
                ('price_delivery', models.FloatField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderIdentificationModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('document_number', models.CharField(max_length=8)),
                ('phone', models.CharField(max_length=10)),
                ('ruc', models.CharField(default=None, max_length=11, null=True)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_identification', to='purchases.ordermodel')),
            ],
            options={
                'db_table': 'order_identification',
            },
        ),
        migrations.CreateModel(
            name='OrderDetailModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('price_unit', models.FloatField()),
                ('price_final', models.FloatField(null=True)),
                ('code', models.CharField(max_length=100, null=True, unique=True)),
                ('subtotal', models.FloatField(null=True)),
                ('discount', models.FloatField(default=0, null=True)),
                ('name_product', models.CharField(max_length=200, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order_detail', to='product.productmodel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='purchases.ordermodel')),
            ],
            options={
                'verbose_name': 'Order Detail',
                'verbose_name_plural': 'Order Details',
                'db_table': 'order_detail',
                'ordering': ['order', 'product'],
            },
        ),
        migrations.CreateModel(
            name='OrderDeliveryModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('street_number', models.CharField(max_length=50)),
                ('reference', models.TextField(null=True)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_delivery', to='purchases.ordermodel')),
            ],
            options={
                'db_table': 'order_delivery',
            },
        ),
        migrations.CreateModel(
            name='OrderPaymentModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('payment_method', models.CharField(max_length=100)),
                ('payment_number', models.CharField(max_length=100, null=True)),
                ('card_type', models.CharField(max_length=100, null=True)),
                ('card_name', models.CharField(max_length=100, null=True)),
                ('country_code', models.CharField(max_length=10, null=True)),
                ('installments', models.IntegerField(null=True)),
                ('payment_data', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_payment', to='purchases.ordermodel')),
            ],
            options={
                'db_table': 'order_payment',
            },
        ),
        migrations.CreateModel(
            name='OrderStoreModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=250, null=True)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_store', to='purchases.ordermodel')),
            ],
            options={
                'db_table': 'order_store',
            },
        ),
        migrations.CreateModel(
            name='OrderUserTempModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=200)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_temp', to='purchases.ordermodel')),
            ],
            options={
                'db_table': 'order_user_temp',
            },
        ),
    ]
