# Generated by Django 5.1 on 2024-09-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdeliverymodel',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderdeliverymodel',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderdeliverymodel',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderdeliverymodel',
            name='province',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderdeliverymodel',
            name='reference',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='orderdeliverymodel',
            name='street',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderpaymentmodel',
            name='payment_method',
            field=models.CharField(max_length=100),
        ),
    ]
