# Generated by Django 5.1 on 2024-09-13 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_orderdeliverymodel_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderusertempmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='orderusertempmodel',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_temp', to='purchases.ordermodel'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
