# Generated by Django 5.1 on 2024-09-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_remove_orderusertempmodel_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpaymentmodel',
            old_name='patment_date',
            new_name='payment_data',
        ),
        migrations.AddField(
            model_name='orderdetailmodel',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderdetailmodel',
            name='name_product',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderdetailmodel',
            name='price_unit',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='total_discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderpaymentmodel',
            name='card_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderpaymentmodel',
            name='card_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderpaymentmodel',
            name='country_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='orderpaymentmodel',
            name='installments',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderpaymentmodel',
            name='payment_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetailmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetailmodel',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderidentificationmodel',
            name='ruc',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
