# Generated by Django 5.1 on 2024-09-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_rename_patment_date_orderpaymentmodel_payment_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='price_delivery',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
