# Generated by Django 5.1 on 2024-09-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_alter_ordermodel_code_alter_ordermodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetailmodel',
            name='discount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetailmodel',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='orderdetailmodel',
            name='price_unit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderdetailmodel',
            name='subtotal',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='orderidentificationmodel',
            name='ruc',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='price_delivery',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='total_discount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='orderpaymentmodel',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderstoremodel',
            name='store_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
