# Generated by Django 5.1 on 2024-09-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_alter_orderdetailmodel_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetailmodel',
            old_name='price',
            new_name='price_final',
        ),
        migrations.AddField(
            model_name='orderdetailmodel',
            name='code',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='orderidentificationmodel',
            name='document_number',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='orderidentificationmodel',
            name='ruc',
            field=models.CharField(default=None, max_length=11, null=True),
        ),
    ]
