# Generated by Django 5.0.1 on 2024-09-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offersmodel',
            options={'verbose_name': 'oferta', 'verbose_name_plural': 'ofertas'},
        ),
        migrations.AlterModelOptions(
            name='storemodel',
            options={'verbose_name': 'tienda', 'verbose_name_plural': 'tiendas'},
        ),
        migrations.AddField(
            model_name='storemodel',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offersmodel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
